version: "3.8"
services:
  devcontainer:
    build: .
    image: python:3.10
    container_name: python3_10-dev

    tty: true
    stdin_open: true

    volumes:
      - ./app:/workspaces

    working_dir: /workspaces

    command: /bin/bash
    # command: dotnet run